export interface MailChimpMarketingApiLink {
    /**
     * As with an HTML 'rel' attribute, this describes the type of link.
     */
    rel: string;
    /**
     * This property contains a fully-qualified URL that can be called to retrieve the linked resource or perform the linked action.
     */
    href: string;
    /**
     * The HTTP method that should be used when accessing the URL defined in 'href'. Possible values: "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", or "HEAD".
     */
    method: MarketingApiMethods;
    /**
     * For GETs, this is a URL representing the schema that the response should conform to.
     */
    targetSchema: string;
    /**
     * For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to.
     */
    schema: string;
}


/**
 * The HTTP method that should be used when accessing the URL defined in 'href'. Possible values: "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", or "HEAD".
 */
export type MarketingApiMethods =
    'GET' |
    'POST' |
    'PUT' |
    'DELETE' |
    'HEAD' |
    'OPTIONS' |
    'PATCH'
;

/**
 * An error generated by the Mailchimp API.
 * @example - {
 *   "type": "https://mailchimp.com/developer/marketing/docs/errors/",
 *   "title": "Resource Not Found",
 *   "status": 404,
 *   "detail": "The requested resource could not be found.",
 *   "instance": "995c5cb0-3280-4a6e-808b-3b096d0bb219"
 * }
 */
export interface MarketingApiErrorResponse {
    /**
     * An absolute URI that identifies the problem type.
     * When dereferenced, it should provide human-readable documentation for the problem type.
     */
    type: string;
    /**
     * A short, human-readable summary of the problem type. It shouldn't change based on the occurrence of the problem, except for purposes of localization.
     */
    title: string;
    /**
     * The HTTP status code (RFC2616, Section 6) generated by the origin server for this occurrence of the problem.
     */
    status: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem. [Learn more about errors](https://mailchimp.com/developer/guides/get-started-with-mailchimp-api-3/#Errors).
     */
    detail: string;
    /**
     * A string that identifies this specific occurrence of the problem. Please provide this ID when contacting support.
     */
    instance: string;
}